// <auto-generated />
using System;
using BackendHospitalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendHospitalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320231515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BackendHospitalProject.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("patient")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("app_users", "public");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("appointment_date");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("appointment_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PatientEmail")
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_email");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_name");

                    b.Property<string>("PatientPhone")
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_phone");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("appointments", "public", t =>
                        {
                            t.HasCheckConstraint("CK_appointments_status", "status IN ('pending','confirmed','completed','cancelled')");
                        });
                });

            modelBuilder.Entity("BackendHospitalProject.Models.DoctorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_user_id");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER")
                        .HasColumnName("available");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT")
                        .HasColumnName("bio");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("REAL")
                        .HasColumnName("consultation_fee");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("license_number");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("specialty");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("INTEGER")
                        .HasColumnName("years_experience");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("doctor_profiles", "public");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT")
                        .HasColumnName("allergies");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("patient")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnosis");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("doctor_id");

                    b.Property<string>("DoctorName")
                        .HasColumnType("TEXT")
                        .HasColumnName("doctor_name");

                    b.Property<string>("LabResults")
                        .HasColumnType("TEXT")
                        .HasColumnName("lab_results");

                    b.Property<string>("Medications")
                        .HasColumnType("TEXT")
                        .HasColumnName("medications");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_id");

                    b.Property<string>("Radiology")
                        .HasColumnType("TEXT")
                        .HasColumnName("radiology");

                    b.Property<string>("Surgeries")
                        .HasColumnType("TEXT")
                        .HasColumnName("surgeries");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_date");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("medical_records", "public");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_user_id");

                    b.Property<string>("BloodType")
                        .HasColumnType("TEXT")
                        .HasColumnName("blood_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("TEXT")
                        .HasColumnName("emergency_contact");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("TEXT")
                        .HasColumnName("emergency_phone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("patient_profiles", "public");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.PatientQRCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("patient_qr_codes", "public");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.Appointment", b =>
                {
                    b.HasOne("BackendHospitalProject.Models.DoctorProfile", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendHospitalProject.Models.PatientProfile", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.DoctorProfile", b =>
                {
                    b.HasOne("BackendHospitalProject.Models.AppUser", "AppUser")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("BackendHospitalProject.Models.DoctorProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.MedicalRecord", b =>
                {
                    b.HasOne("BackendHospitalProject.Models.DoctorProfile", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId");

                    b.HasOne("BackendHospitalProject.Models.PatientProfile", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.PatientProfile", b =>
                {
                    b.HasOne("BackendHospitalProject.Models.AppUser", "AppUser")
                        .WithOne("PatientProfile")
                        .HasForeignKey("BackendHospitalProject.Models.PatientProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.PatientQRCode", b =>
                {
                    b.HasOne("BackendHospitalProject.Models.PatientProfile", "Patient")
                        .WithMany("QRCodes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.AppUser", b =>
                {
                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.DoctorProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("BackendHospitalProject.Models.PatientProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");

                    b.Navigation("QRCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
